CREATE TABLE IF NOT EXISTS MASTERS.ACCOUNT_STATE (
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR (50),
    EMAIL VARCHAR (255),
    CREATED_DATE TIMESTAMP NOT NULL,
    MODIFIED_DATE TIMESTAMP NOT NULL);