spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo
    username: postgres
    password: 123456
  flyway:
    locations: classpath:db-migration

swagger-ui:
  server:
    url: localhost:8080

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
