jwt:
    expirationMs: '86400000'
    secret: 'DEMOApp$f58BmDC)&?O!19#P:'

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/jooq-demo
    username: postgres
    password: 123456
  flyway:
    locations: classpath:db-migration

swagger-ui:
  server:
    url: 'http://localhost:8080'

logging:
  level:
    org:
      jooq:
        tools:
          LoggerListener: DEBUG
